# Generated by Django 4.2.6 on 2023-10-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('points', models.FloatField()),
                ('position', models.CharField(max_length=100)),
                ('no_team', models.IntegerField(default=0)),
            ],
        ),
    ]
